server:
  port: 8088
spring:
  main:
    allow-bean-definition-overriding: true
userConfig:
  # 多个选项用空格隔开
  botNames: ''
  qqList: '2364785635'
  pwList: '199605190013zhb?'
scheduled:
  # 每5分钟监听一次B站动态
  biliJob: 0 */5 * * * ?
  # 每天早8点播报干员庆生
  birthdayJob: 0 0 8 */1 * ?
  # 每10分钟检查一次数据更新
  updateJob: 0 */10 * * * ?
  # 每周日晚5点剿灭提醒
  exterminateJob: 0 0 17 ? * SUN
  # 每天4点抽卡次数清空
  cleanJob: 0 0 4 */1 * ?
baiduConfig:
  APP_ID: 26369469
  API_KEY: E6E9xPFH2OSZSv4x6rOnaIHr
  SECRET_KEY: m4SrIWWQo8Xl9pw4aaqjHxoi8QeWv6lp